### ISSUE TITLE
Enemy can phase through objects

### ISSUE THREAD

**Issue by Grochoci** [canadianbif/Symbiosis#14]
If you kite the GreenZomb in room3 to the left of the pipes, and then move quickly to the right of them, the enemy will actually run THROUGH the pipes and attack you.

Probably same problem as with the player/bullets and the wall. Must look at colliders and the whole rigidbody continuous/dynamic stuff, could be a fix for everything somewhere here!

**Comment by federbenjamin** [comment]
The path finding static area just needs to be baked again, will solve when cleaning up AI1.
