### ISSUE TITLE
Random dying bug!!

### ISSUE THREAD

**Issue by federbenjamin** [canadianbif/Symbiosis#15]
Sometimes you randomly go to the gameover screen even though your health is full... anyone who can please look into this

**Comment by Grochoci** [comment]
Any Specific circumstances that this happens?

**Comment by federbenjamin** [comment]
![screen shot 2016-03-29 at 7 36 40 am](https://cloud.githubusercontent.com/assets/1878213/14108293/a5435870-f58a-11e5-80e1-55c96ffc358a.png)

I think something to do with this
